<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Hiv;

class HivSeeder extends Seeder
{
    public function run(): void
    {
        $data = [
            ['kecamatan' => 'Cisewu', 'total_kasus' => 1, 'tahun' => 2022],
            ['kecamatan' => 'Caringin', 'total_kasus' => 4, 'tahun' => 2022],
            ['kecamatan' => 'Talegong', 'total_kasus' => 0, 'tahun' => 2022],
            ['kecamatan' => 'Bungbulang', 'total_kasus' => 0, 'tahun' => 2022],
            ['kecamatan' => 'Mekarmukti', 'total_kasus' => 0, 'tahun' => 2022],
            ['kecamatan' => 'Pamulihan', 'total_kasus' => 0, 'tahun' => 2022],
            ['kecamatan' => 'Pakenjeng', 'total_kasus' => 0, 'tahun' => 2022],
            ['kecamatan' => 'Cikelet', 'total_kasus' => 1, 'tahun' => 2022],
            ['kecamatan' => 'Pameungpeuk', 'total_kasus' => 2, 'tahun' => 2022],
            ['kecamatan' => 'Cibalong', 'total_kasus' => 0, 'tahun' => 2022],
            ['kecamatan' => 'Cisompet', 'total_kasus' => 0, 'tahun' => 2022],
            ['kecamatan' => 'Peundeuy', 'total_kasus' => 0, 'tahun' => 2022],
            ['kecamatan' => 'Singajaya', 'total_kasus' => 0, 'tahun' => 2022],
            ['kecamatan' => 'Cihurip', 'total_kasus' => 0, 'tahun' => 2022],
            ['kecamatan' => 'Cikajang', 'total_kasus' => 5, 'tahun' => 2022],
            ['kecamatan' => 'Banjarwangi', 'total_kasus' => 0, 'tahun' => 2022],
            ['kecamatan' => 'Cilawu', 'total_kasus' => 0, 'tahun' => 2022],
            ['kecamatan' => 'Bayongbong', 'total_kasus' => 0, 'tahun' => 2022],
            ['kecamatan' => 'Cigedug', 'total_kasus' => 0, 'tahun' => 2022],
            ['kecamatan' => 'Cisurupan', 'total_kasus' => 1, 'tahun' => 2022],
            ['kecamatan' => 'Sukaresmi', 'total_kasus' => 0, 'tahun' => 2022],
            ['kecamatan' => 'Samarang', 'total_kasus' => 3, 'tahun' => 2022],
            ['kecamatan' => 'Pasirwangi', 'total_kasus' => 0, 'tahun' => 2022],
            ['kecamatan' => 'Tarogong Kidul', 'total_kasus' => 0, 'tahun' => 2022],
            ['kecamatan' => 'Tarogong Kaler', 'total_kasus' => 5, 'tahun' => 2022],
            ['kecamatan' => 'Garut Kota', 'total_kasus' => 7, 'tahun' => 2022],
            ['kecamatan' => 'Karangpawitan', 'total_kasus' => 1, 'tahun' => 2022],
            ['kecamatan' => 'Wanaraja', 'total_kasus' => 1, 'tahun' => 2022],
            ['kecamatan' => 'Sucinaraja', 'total_kasus' => 0, 'tahun' => 2022],
            ['kecamatan' => 'Pangatikan', 'total_kasus' => 1, 'tahun' => 2022],
            ['kecamatan' => 'Sukawening', 'total_kasus' => 1, 'tahun' => 2022],
            ['kecamatan' => 'Karangtengah', 'total_kasus' => 0, 'tahun' => 2022],
            ['kecamatan' => 'Banyuresmi', 'total_kasus' => 4, 'tahun' => 2022],
            ['kecamatan' => 'Leles', 'total_kasus' => 9, 'tahun' => 2022],
            ['kecamatan' => 'Leuwigoong', 'total_kasus' => 0, 'tahun' => 2022],
            ['kecamatan' => 'Cibatu', 'total_kasus' => 3, 'tahun' => 2022],
            ['kecamatan' => 'Kersamanah', 'total_kasus' => 3, 'tahun' => 2022],
            ['kecamatan' => 'Cibiuk', 'total_kasus' => 0, 'tahun' => 2022],
            ['kecamatan' => 'Kadungora', 'total_kasus' => 0, 'tahun' => 2022],
            ['kecamatan' => 'Blubur Limbangan', 'total_kasus' => 6, 'tahun' => 2022],
            ['kecamatan' => 'Selaawi', 'total_kasus' => 0, 'tahun' => 2022],
            ['kecamatan' => 'Malangbong', 'total_kasus' => 1, 'tahun' => 2022],
            

            ['kecamatan' => 'Cisewu', 'total_kasus' => 1, 'tahun' => 2023],
            ['kecamatan' => 'Caringin', 'total_kasus' => 4, 'tahun' => 2023],
            ['kecamatan' => 'Talegong', 'total_kasus' => 0, 'tahun' => 2023],
            ['kecamatan' => 'Bungbulang', 'total_kasus' => 0, 'tahun' => 2023],
            ['kecamatan' => 'Mekarmukti', 'total_kasus' => 0, 'tahun' => 2023],
            ['kecamatan' => 'Pamulihan', 'total_kasus' => 0, 'tahun' => 2023],
            ['kecamatan' => 'Pakenjeng', 'total_kasus' => 0, 'tahun' => 2023],
            ['kecamatan' => 'Cikelet', 'total_kasus' => 1, 'tahun' => 2023],
            ['kecamatan' => 'Pameungpeuk', 'total_kasus' => 2, 'tahun' => 2023],
            ['kecamatan' => 'Cibalong', 'total_kasus' => 0, 'tahun' => 2023],
            ['kecamatan' => 'Cisompet', 'total_kasus' => 0, 'tahun' => 2023],
            ['kecamatan' => 'Peundeuy', 'total_kasus' => 0, 'tahun' => 2023],
            ['kecamatan' => 'Singajaya', 'total_kasus' => 0, 'tahun' => 2023],
            ['kecamatan' => 'Cihurip', 'total_kasus' => 0, 'tahun' => 2023],
            ['kecamatan' => 'Cikajang', 'total_kasus' => 5, 'tahun' => 2023],
            ['kecamatan' => 'Banjarwangi', 'total_kasus' => 0, 'tahun' => 2023],
            ['kecamatan' => 'Cilawu', 'total_kasus' => 0, 'tahun' => 2023],
            ['kecamatan' => 'Bayongbong', 'total_kasus' => 0, 'tahun' => 2023],
            ['kecamatan' => 'Cigedug', 'total_kasus' => 0, 'tahun' => 2023],
            ['kecamatan' => 'Cisurupan', 'total_kasus' => 1, 'tahun' => 2023],
            ['kecamatan' => 'Sukaresmi', 'total_kasus' => 0, 'tahun' => 2023],
            ['kecamatan' => 'Samarang', 'total_kasus' => 3, 'tahun' => 2023],
            ['kecamatan' => 'Pasirwangi', 'total_kasus' => 0, 'tahun' => 2023],
            ['kecamatan' => 'Tarogong Kidul', 'total_kasus' => 0, 'tahun' => 2023],
            ['kecamatan' => 'Tarogong Kaler', 'total_kasus' => 5, 'tahun' => 2023],
            ['kecamatan' => 'Garut Kota', 'total_kasus' => 7, 'tahun' => 2023],
            ['kecamatan' => 'Karangpawitan', 'total_kasus' => 1, 'tahun' => 2023],
            ['kecamatan' => 'Wanaraja', 'total_kasus' => 1, 'tahun' => 2023],
            ['kecamatan' => 'Sucinaraja', 'total_kasus' => 0, 'tahun' => 2023],
            ['kecamatan' => 'Pangatikan', 'total_kasus' => 1, 'tahun' => 2023],
            ['kecamatan' => 'Sukawening', 'total_kasus' => 1, 'tahun' => 2023],
            ['kecamatan' => 'Karangtengah', 'total_kasus' => 0, 'tahun' => 2023],
            ['kecamatan' => 'Banyuresmi', 'total_kasus' => 4, 'tahun' => 2023],
            ['kecamatan' => 'Leles', 'total_kasus' => 9, 'tahun' => 2023],
            ['kecamatan' => 'Leuwigoong', 'total_kasus' => 0, 'tahun' => 2023],
            ['kecamatan' => 'Cibatu', 'total_kasus' => 3, 'tahun' => 2023],
            ['kecamatan' => 'Kersamanah', 'total_kasus' => 3, 'tahun' => 2023],
            ['kecamatan' => 'Cibiuk', 'total_kasus' => 0, 'tahun' => 2023],
            ['kecamatan' => 'Kadungora', 'total_kasus' => 0, 'tahun' => 2023],
            ['kecamatan' => 'Blubur Limbangan', 'total_kasus' => 6, 'tahun' => 2023],
            ['kecamatan' => 'Selaawi', 'total_kasus' => 0, 'tahun' => 2023],
            ['kecamatan' => 'Malangbong', 'total_kasus' => 1, 'tahun' => 2023],

            ['kecamatan' => 'Cisewu', 'total_kasus' => 1, 'tahun' => 2024],
            ['kecamatan' => 'Caringin', 'total_kasus' => 2, 'tahun' => 2024],
            ['kecamatan' => 'Talegong', 'total_kasus' => 0, 'tahun' => 2024],
            ['kecamatan' => 'Bungbulang', 'total_kasus' => 1, 'tahun' => 2024],
            ['kecamatan' => 'Mekarmukti', 'total_kasus' => 0, 'tahun' => 2024],
            ['kecamatan' => 'Pamulihan', 'total_kasus' => 0, 'tahun' => 2024],
            ['kecamatan' => 'Pakenjeng', 'total_kasus' => 1, 'tahun' => 2024],
            ['kecamatan' => 'Cikelet', 'total_kasus' => 3, 'tahun' => 2024],
            ['kecamatan' => 'Pameungpeuk', 'total_kasus' => 1, 'tahun' => 2024],
            ['kecamatan' => 'Cibalong', 'total_kasus' => 0, 'tahun' => 2024],
            ['kecamatan' => 'Cisompet', 'total_kasus' => 0, 'tahun' => 2024],
            ['kecamatan' => 'Peundeuy', 'total_kasus' => 4, 'tahun' => 2024],
            ['kecamatan' => 'Singajaya', 'total_kasus' => 2, 'tahun' => 2024],
            ['kecamatan' => 'Cihurip', 'total_kasus' => 0, 'tahun' => 2024],
            ['kecamatan' => 'Cikajang', 'total_kasus' => 48, 'tahun' => 2024],
            ['kecamatan' => 'Banjarwangi', 'total_kasus' => 1, 'tahun' => 2024],
            ['kecamatan' => 'Cilawu', 'total_kasus' => 3, 'tahun' => 2024],
            ['kecamatan' => 'Bayongbong', 'total_kasus' => 3, 'tahun' => 2024],
            ['kecamatan' => 'Cigedug', 'total_kasus' => 1, 'tahun' => 2024],
            ['kecamatan' => 'Cisurupan', 'total_kasus' => 8, 'tahun' => 2024],
            ['kecamatan' => 'Sukaresmi', 'total_kasus' => 0, 'tahun' => 2024],
            ['kecamatan' => 'Samarang', 'total_kasus' => 5, 'tahun' => 2024],
            ['kecamatan' => 'Pasirwangi', 'total_kasus' => 1, 'tahun' => 2024],
            ['kecamatan' => 'Tarogong Kidul', 'total_kasus' => 2, 'tahun' => 2024],
            ['kecamatan' => 'Tarogong Kaler', 'total_kasus' => 9, 'tahun' => 2024],
            ['kecamatan' => 'Garut Kota', 'total_kasus' => 11, 'tahun' => 2024],
            ['kecamatan' => 'Karangpawitan', 'total_kasus' => 5, 'tahun' => 2024],
            ['kecamatan' => 'Wanaraja', 'total_kasus' => 1, 'tahun' => 2024],
            ['kecamatan' => 'Sucinaraja', 'total_kasus' => 0, 'tahun' => 2024],
            ['kecamatan' => 'Pangatikan', 'total_kasus' => 9, 'tahun' => 2024],
            ['kecamatan' => 'Sukawening', 'total_kasus' => 0, 'tahun' => 2024],
            ['kecamatan' => 'Karangtengah', 'total_kasus' => 0, 'tahun' => 2024],
            ['kecamatan' => 'Banyuresmi', 'total_kasus' => 6, 'tahun' => 2024],
            ['kecamatan' => 'Leles', 'total_kasus' => 2, 'tahun' => 2024],
            ['kecamatan' => 'Leuwigoong', 'total_kasus' => 2, 'tahun' => 2024],
            ['kecamatan' => 'Cibatu', 'total_kasus' => 1, 'tahun' => 2024],
            ['kecamatan' => 'Kersamanah', 'total_kasus' => 4, 'tahun' => 2024],
            ['kecamatan' => 'Cibiuk', 'total_kasus' => 0, 'tahun' => 2024],
            ['kecamatan' => 'Kadungora', 'total_kasus' => 1, 'tahun' => 2024],
            ['kecamatan' => 'Blubur Limbangan', 'total_kasus' => 3, 'tahun' => 2024],
            ['kecamatan' => 'Selaawi', 'total_kasus' => 1, 'tahun' => 2024],
            ['kecamatan' => 'Malangbong', 'total_kasus' => 4, 'tahun' => 2024],
        ];

        foreach ($data as $item) {
            Hiv::create($item);
        }
    }
}
